import { PortalState } from "@/types/portal";

export const INITIAL_PORTAL_STATE: PortalState = {
  view: { type: "ticket-list" },
  users: [
    { id: "U1", name: "Jane Doe", email: "jane@example.com", avatarInitials: "JD" },
    { id: "U2", name: "Bob Smith", email: "bob@example.com", avatarInitials: "BS" },
    { id: "U3", name: "Carol Lee", email: "carol@example.com", avatarInitials: "CL" },
    { id: "U4", name: "Dan Brown", email: "dan@example.com", avatarInitials: "DB" },
  ],
  tickets: [
    {
      id: "TKT-001",
      subject: "Cannot login to account",
      status: "Open",
      priority: "Critical",
      userId: "U1",
      description: "User reports complete inability to access their account after password reset.",
      createdAt: "2024-01-15T09:00:00Z",
      updatedAt: "2024-01-15T09:00:00Z",
      replies: [],
      tags: ["auth", "urgent"],
    },
    {
      id: "TKT-002",
      subject: "Payment gateway error",
      status: "Open",
      priority: "High",
      userId: "U2",
      description: "Payment fails at checkout with error code 402.",
      createdAt: "2024-01-14T10:00:00Z",
      updatedAt: "2024-01-14T10:00:00Z",
      replies: [],
      tags: ["billing"],
    },
    {
      id: "TKT-003",
      subject: "Feature request: dark mode",
      status: "Open",
      priority: "Low",
      userId: "U1",
      description: "Would love a dark mode option.",
      createdAt: "2024-01-13T11:00:00Z",
      updatedAt: "2024-01-13T11:00:00Z",
      replies: [],
      tags: ["feature-request"],
    },
    {
      id: "TKT-004",
      subject: "Export to CSV broken",
      status: "In Progress",
      priority: "Medium",
      userId: "U3",
      description: "CSV export produces empty file.",
      createdAt: "2024-01-12T08:00:00Z",
      updatedAt: "2024-01-16T08:00:00Z",
      replies: [],
      tags: ["data-export"],
    },
    {
      id: "TKT-005",
      subject: "Billing address not saving",
      status: "Open",
      priority: "High",
      userId: "U1",
      description: "Billing address reverts to old address after save.",
      createdAt: "2024-01-11T14:00:00Z",
      updatedAt: "2024-01-11T14:00:00Z",
      replies: [],
      tags: ["billing", "profile"],
    },
    {
      id: "TKT-006",
      subject: "Mobile app crashes on startup",
      status: "Open",
      priority: "Critical",
      userId: "U4",
      description: "App crashes immediately on iOS 17.",
      createdAt: "2024-01-10T07:00:00Z",
      updatedAt: "2024-01-10T07:00:00Z",
      replies: [],
      tags: ["mobile", "crash"],
    },
    {
      id: "TKT-007",
      subject: "Notification emails not sending",
      status: "Resolved",
      priority: "Medium",
      userId: "U2",
      description: "Resolved by re-enabling SMTP config.",
      createdAt: "2024-01-09T13:00:00Z",
      updatedAt: "2024-01-17T13:00:00Z",
      replies: [],
      tags: ["email"],
    },
    {
      id: "TKT-008",
      subject: "Slow dashboard loading",
      status: "Open",
      priority: "Low",
      userId: "U3",
      description: "Dashboard takes 15+ seconds to load.",
      createdAt: "2024-01-08T16:00:00Z",
      updatedAt: "2024-01-08T16:00:00Z",
      replies: [],
      tags: ["performance"],
    },
  ],
};
