/**
 * Fetches MMLU questions from HuggingFace and generates src/lib/benchmark/questions.ts
 * Run with: node scripts/curate-mmlu.mjs
 */

import { writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

const SUBJECTS = [
  { mmlu: "college_computer_science", category: "cs" },
  { mmlu: "computer_security",        category: "cs" },
  { mmlu: "electrical_engineering",   category: "engineering" },
  { mmlu: "machine_learning",         category: "engineering" },
  { mmlu: "abstract_algebra",         category: "math" },
  { mmlu: "college_mathematics",      category: "math" },
  { mmlu: "high_school_statistics",   category: "math" },
  { mmlu: "college_physics",          category: "science" },
  { mmlu: "college_chemistry",        category: "science" },
  { mmlu: "college_biology",          category: "science" },
];

const PER_SUBJECT = 20;
const ANSWER_LETTERS = ["A", "B", "C", "D"];

function assignDifficulty(index, total) {
  const pos = index / total;
  if (pos < 0.35) return "easy";
  if (pos < 0.70) return "medium";
  return "hard";
}

async function fetchSubject(mmluSubject, limit) {
  const url =
    `https://datasets-server.huggingface.co/rows` +
    `?dataset=cais%2Fmmlu` +
    `&config=${encodeURIComponent(mmluSubject)}` +
    `&split=test` +
    `&offset=0` +
    `&limit=${limit}`;

  const res = await fetch(url);
  if (!res.ok) {
    throw new Error(`Failed to fetch ${mmluSubject}: ${res.status} ${res.statusText}`);
  }
  const data = await res.json();
  return data.rows ?? [];
}

async function main() {
  const questions = [];

  for (const { mmlu, category } of SUBJECTS) {
    console.log(`Fetching ${mmlu}...`);
    const rows = await fetchSubject(mmlu, PER_SUBJECT);

    rows.forEach((entry, i) => {
      const q = entry.row;
      const shortSubject = mmlu.replace(/college_|high_school_/g, "").replace(/_/g, "-");
      const id = `${shortSubject}-${String(i + 1).padStart(2, "0")}`;

      questions.push({
        id,
        subject: category,
        difficulty: assignDifficulty(i, rows.length),
        text: q.question,
        choices: q.choices,
        expectedAnswer: ANSWER_LETTERS[q.answer],
      });
    });

    console.log(`  → ${rows.length} questions (subject: ${category})`);
  }

  // Proportional per-subject counts for each run size
  // Total: cs=40, engineering=40, math=60, science=60
  const SAMPLING = {
    10:  { cs: 2, engineering: 2, math: 3, science: 3 },
    20:  { cs: 4, engineering: 4, math: 6, science: 6 },
    40:  { cs: 8, engineering: 8, math: 12, science: 12 },
  };

  const output = `// Auto-generated by scripts/curate-mmlu.mjs — do not edit manually
// Run: node scripts/curate-mmlu.mjs
import { Question, Subject } from "@/types/agent";

export const QUESTIONS: Question[] = ${JSON.stringify(questions, null, 2)};

export function getRandomQuestions(count: 10 | 20 | 40): Question[] {
  const SAMPLING: Record<number, Record<Subject, number>> = ${JSON.stringify(SAMPLING, null, 2)} as Record<number, Record<Subject, number>>;

  const subjects = ["cs", "engineering", "math", "science"] as Subject[];
  const allPicked: Question[] = [];

  for (const subject of subjects) {
    const pool = QUESTIONS.filter((q) => q.subject === subject);
    const n = SAMPLING[count][subject];
    // Fisher-Yates shuffle then slice
    const shuffled = [...pool];
    for (let i = shuffled.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
    }
    allPicked.push(...shuffled.slice(0, n));
  }

  // Final shuffle
  for (let i = allPicked.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [allPicked[i], allPicked[j]] = [allPicked[j], allPicked[i]];
  }

  return allPicked;
}
`;

  const outPath = resolve(__dirname, "../src/lib/benchmark/questions.ts");
  writeFileSync(outPath, output, "utf8");
  console.log(`\nWrote ${questions.length} questions to ${outPath}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
